name: FedRAMP Remediation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  remediate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::941355383184:role/Bedrock-Github-github-actions-bedrock-role
          aws-region: us-east-1

      - name: Run FedRAMP Remediation Agent
        uses: CheckmarxDev/fedramp-remediation-agent@GHAction
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          jira_base_url: ${{ secrets.JIRA_BASE_URL_FEDRAMP }}
          jira_email: ${{ secrets.JIRA_USER_EMAIL_FEDRAMP }}
          jira_apikey: ${{ secrets.JIRA_API_TOKEN_FEDRAMP }}
          aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ env.AWS_SESSION_TOKEN }}

