name: FedRAMP Remediation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  remediate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::941355383184:role/Bedrock-Github-github-actions-bedrock-role
          aws-region: us-east-1

      - name: Run FedRAMP Remediation Agent
        uses: CheckmarxDev/fedramp-remediation-agent@groundcoverForFedrampAgent
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          jira_base_url: ${{ vars.JIRA_BASE_URL_FEDRAMP }}
          jira_email: ${{ secrets.JIRA_USER_EMAIL_FEDRAMP }}
          jira_apikey: ${{ secrets.JIRA_API_TOKEN_FEDRAMP }}
          otel_endpoint: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          groundcover_api_key: ${{ secrets.GROUNDCOVER_API_KEY }}
          groundcover_backend_id: ${{ secrets.GROUNDCOVER_BACKEND_ID }}

